# common settings
version: 1
disable_existing_loggers: false
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -



# formatters
formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

    detailed:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s - %(funcName)s() [%(lineno)s] : %(message)s"

    error:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s() [%(lineno)s] : %(message)s"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


# filters
filters:
    # catches logs !only! with INFO level
    INFOFilter:
        # path to filter from the core package
        (): tg_note_bot.utils.logging_.filters.LevelFilter
        level: INFO

    # catches logs !only! with DEBUG level
    DEBUGFilter:
        # path to filter from the core package
        (): tg_note_bot.utils.logging_.filters.LevelFilter
        level: DEBUG

# handlers
handlers:
    # only INFO logs
    info_console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout
        filters: [INFOFilter]

    # only DEBUG logs
    debug_console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: detailed
        stream: ext://sys.stdout
        filters: [DEBUGFilter]

    # WARN and higher logs
    error_console:
        class: logging.StreamHandler
        level: WARN
        formatter: error
        stream: ext://sys.stderr

    # INFO and higher logs
    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: detailed
        filename: /~tmp/logs/common/info.log
        maxBytes: 1000000 # 1MB
        backupCount: 3
        encoding: utf8

    # ERROR and higher logs
    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: /~tmp/logs/common/errors.log
        maxBytes: 1000000 # 1MB
        backupCount: 5
        encoding: utf8

    # ERROR and higher logs that have been emitted !only! by `tg_note_bot_logger`
    tg_note_bot_logger_error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: /~tmp/logs/tg_note_bot/errors.log
        maxBytes: 1000000 # 1MB
        backupCount: 5
        encoding: utf8
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


# root logger
root:
    level: INFO
    handlers: [debug_console, info_console, error_console, info_file_handler, error_file_handler]
    propogate: yes
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


# loggers
loggers:
    # name of the main package
    tg_note_bot:
        level: INFO
        handlers: [tg_note_bot_logger_error_file_handler]
        propogate: yes
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -