# common settings
version: 1
disable_existing_loggers: false
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -



# formatters
formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

    error:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s() [%(lineno)s] : %(message)s"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


# filters
filters:
    INFOFilter:
        # path to filter from the core package
        (): tg_note_bot.utils.logging_.filters.LevelFilter
        level: INFO


# handlers
handlers:
    info_console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout
        filters: [INFOFilter]

    error_console:
        class: logging.StreamHandler
        level: WARN
        formatter: error
        stream: ext://sys.stderr

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        # path to filter from the core package
        filename: ../logs/common/errors.log
        maxBytes: 1000000 # 1MB
        backupCount: 5
        encoding: utf8

    tg_note_bot_logger_error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        # path to filter from the core package
        filename: ../logs/tg_note_bot/errors.log
        maxBytes: 1000000 # 1MB
        backupCount: 5
        encoding: utf8
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


# root logger
root:
    level: NOTSET
    handlers: [info_console, error_console, error_file_handler]
    propogate: yes
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


# loggers
loggers:
    # name of the main package
    tg_note_bot:
        level: INFO
        handlers: [tg_note_bot_logger_error_file_handler]
        propogate: yes
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -