/*
	This file is generated by `database_initialization` package.
	Version of the `models.py`: 1.0
	Time of the generation [UTC]: 2021-04-29 14:34:07
*/

	/* The start of sql code */

CREATE TABLE users (
	id BIGINT NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id)
);

CREATE TABLE bugs (
	id BIGSERIAL NOT NULL, 
	message VARCHAR NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	is_shown BOOLEAN DEFAULT 'false', 
	user_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE TABLE rubrics (
	id BIGSERIAL NOT NULL, 
	name VARCHAR NOT NULL, 
	description VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	user_id BIGINT NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE TABLE links (
	id BIGSERIAL NOT NULL, 
	url VARCHAR NOT NULL, 
	description VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	user_id BIGINT NOT NULL, 
	rubric_id BIGINT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(rubric_id) REFERENCES rubrics (id) ON DELETE SET NULL
);